name: Compile LaTeX CV

on:
  push:
    branches:
      - main  # Adjust to your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX environment
        uses: xu-cheng/latex-action@v3
        with:
          root_file: CV_Gagandeep_Updated.tex
          compiler: pdflatex  # Lowercase 'pdflatex'

      - name: Commit compiled PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CV_Gagandeep_Updated.pdf
          git commit -m "Auto-compiled CV PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token to authenticate push
